### ISSUE TITLE
bug avec génération du manifest de l'opf en cas de sous-répertoires

### ISSUE THREAD

**Issue by garconvacher** [civodulab/epubtools#14]
Si des sous-répertoires sont présents dans la structure, le manifest de l'opf comporte des erreurs d'écriture dans le chemin : `\` à la place de `/`
ex : `rep1/rep2/fichier.xhtml` donne :
`<item id="fichier" href="rep1\rep2/fichier.xhtml" media-type="application/xhtml+xml" />`

**Comment by civodulab** [comment]
Corrigé avec la version 1.8.4
