### ISSUE TITLE
Opens search bar each time VS Code starts

### ISSUE THREAD

**Issue by thephilgray** [civodulab/epubtools#18]
When I start VS Code, the extensions initialize, and then the search bar opens. I disabled my extensions one-by-one and identified this `epubtools` as the one causing this unexpected behavior.

I'm not familiar with extension development, but I noticed this line in `extension.js`: 
```js
vscode.commands.executeCommand('workbench.view.search');
```
I don't understand why it's necessary to open the search bar each time the extension initializes, but I'd suggest making it clear in the readme.

Thanks!

**System details** 
ProductName:	Mac OS X
ProductVersion: 10.14.2
BuildVersion: 18C54
Code: Version 1.30.2 (1.30.2)
Epub Tools: 1.9.9

**Comment by civodulab** [comment]
Thank you for the feedback.
Corrected with version 1.9.10
