### ISSUE TITLE
A11Y/Dpub ARIA roles dans <nav epub:type="landmarks">

### ISSUE THREAD

**Issue by garconvacher** [civodulab/epubtools#19]
Les roles ARIA Dpub dans les éléments contenus dans la `<nav epub:type="landmarks">` génèrent une erreur dans Epubcheck 4.2.

**Comment by garconvacher** [comment]
Mais pas dans epubcheck 4.1.
À voir si c'est un bug ou pas.
https://github.com/w3c/epubcheck/issues/965

**Comment by garconvacher** [comment]
@civodulab, ils ne sont effectivement pas nécessaires.

**Comment by civodulab** [comment]
Ok modifié dans la version 1.10.0
