### ISSUE TITLE
Possibilité de créer une ancre dans les <h> des xhtml ?

### ISSUE THREAD

**Issue by garconvacher** [civodulab/epubtools#2]
La construction de la TOC récupère les titres dans les fichiers xhtml et s'il n'y a pas d'ancre dans les `<h>`, c'est le nom du fichier qui est pointé par les liens.
Est-ce qu'il est possible de créer des ancres dans les `<h>` qui n'en n'ont pas pour avoir une navigation plus aboutie ?

**Comment by civodulab** [comment]
Intégré dans la version 1.3.0.
Et merci pour le bug du manifest
