### ISSUE TITLE
Les pages sans titres (EpubTools: Table des matières)

### ISSUE THREAD

**Issue by garconvacher** [civodulab/epubtools#3]
Dis @civodulab, je viens d'avoir le coup : des pages qui n’apparaissent pas dans la TOC car il n'y a aucun lien sur celles-ci. Ça serait pas mal de pouvoir les identifier pour traiter le problème.

**Comment by civodulab** [comment]
Ajouté dans la version 1.4.6. Indique le ou les fichiers qui n'ont pas de titre lors de l'ajout de la table des matières
