### ISSUE TITLE
"premier <h.> dans <title>" copie l'intégralité du contenu de la balise <h>

### ISSUE THREAD

**Issue by garconvacher** [civodulab/epubtools#5]
La fonction "premier <h.> dans <title>" copie le contenu du `<h>` y compris les balises présentes.
Supposons qu'un collègue vous ait collé dans un `<h>` des `<span>` avec un `id`... ben on se retrouve avec un doublon :-)

**Comment by garconvacher** [comment]
Et si on a pas fait gaffe, on se retrouve avec des spans dans le .ncx et la toc aussi :)

**Comment by civodulab** [comment]
Corrigé dans la prochaine version
